Psychedelic/plug

source/Popup/Views/Deposit/styles.js, source/components/CopyButton/styles.js
- Use opacity transition instead to prevent Firefox flicker on icon hover
- [ch23231](https://app.clubhouse.io/terminalsystems/story/23231/deposit-page-minor-twitch-while-hovering-over-copy-buttons-and-copying)
Previously:
https://user-images.githubusercontent.com/236752/125444648-73fe1c11-ca34-45c2-8e93-225e3f9301df.mp4
Current:
https://user-images.githubusercontent.com/236752/125444088-71c88541-fae6-4df6-ae7c-904d625d6119.mp4
=> style: 💄 use opacity transition instead

package.json, yarn.lock
- Runtime type check for whitelist argument on requestConnect call
- Use plug-inpage-provider, version 1.1.11
- Updated yarn.lock
Pending dependency https://github.com/Psychedelic/plug-inpage-provider/pull/22
and https://github.com/Psychedelic/plug/pull/139
=> refactor:  💡 whitelist handler

source/Background/Controller.js
- Changed response from handleAllowAgent to respond instead of throw, to allow the modal to close
=> Fix: fixed connection modal not closing on decline

source/Pages/Notification/components/AllowAgent/index.jsx, source/components/Apps/index.jsx, source/components/Apps/styles.js, source/locales/en/translation.json, source/ui/AppItem/index.jsx, source/ui/AppItem/styles.js, source/ui/WhitelistContainer/index.jsx, source/ui/WhitelistContainer/styles.js, source/ui/WhitelistItem/index.jsx, source/ui/WhitelistItem/styles.js, source/ui/index.js
- [enhance-allow-users-to-see-whitelisted-canisters-in-the-extension](https://app.clubhouse.io/terminalsystems/story/23401/enhance-allow-users-to-see-whitelisted-canisters-in-the-extension)
=> show whitelisted canister ids on apps

source/Background/Controller.js, source/Background/errors.js, source/Pages/Notification/components/AllowAgent/index.jsx, source/Pages/Notification/components/AppConnection/index.jsx, source/Pages/Notification/components/NotificationError/index.jsx, source/Pages/Notification/components/NotificationError/styles.js, source/Pages/Notification/components/Transfer/hooks/useRequests.jsx, source/Pages/Notification/components/Transfer/index.jsx, source/Popup/Views/Error/index.jsx, source/locales/en/translation.json
- Ensure locks are updated by calling `init`.
- Added `NotificationError` screen
- Rewired flow to return false when an unexpected error occurs, generally because the user locks the extension while having a popup open
=> Fix: Connect/AllowAgent silent fail

source/Popup/Views/Send/hooks/useSteps.jsx
- Remove fee from avail balance on app reopen when on send screen
=> Removed fee from avail on send reopen

source/Popup/Views/Home/index.jsx, source/components/NFTs/index.jsx
- Added request at home render
- Removed validation on empty collections for loading
https://app.shortcut.com/terminalsystems/story/23962/fix-nft-cache
=> Fix NFT Cache

source/Background/Controller.js, source/Popup/app.jsx
- Fixed issue when keyring being undefined after extension restart
Recreating as seems previous PR being overwritten
=> Keyring undefined fix

source/Popup/Views/NFTDetails/index.jsx
- Remove `type=thumbnail` from `nft?.url` on `nfts.expandNFT` button.
None
__The button in question.__
I believe this is a UX improvement. The technical implementation could be maybe a little tidier, if someone more familiar with the application wants to correct me.
The button seems to express the intent to see a "full" version of the NFT. When it then displays a thumbnail version, that would be jarring to the end user. This is corroborated by the first users of the Saga Legends NFT series.
Each NFT project has it's own implementation and I wouldn't ask for something that made my project better while making others' worse. AFAIK these preview URLs are not explicitly prescribed by any EXT documentation or other standard docs. For that reason, testing on a wallet that contains one of each …
=> Remove thumbnail type from nft view link

source/Popup/Views/SendNFT/index.jsx
- Fixed error where a failed nft send would not show any errors and just redirect to the nfts screen.
https://app.shortcut.com/terminalsystems/story/24480/fix-nft-send
=> Fixed error message not being shown on a failed nft transfer

source/ui/ActivityItem/styles.js, source/ui/CanisterInfo/components/Item/styles.js, source/ui/IncomingAction/styles.js
- made app icons rounded square
- [sc24481](https://app.shortcut.com/terminalsystems/story/24481/fix-make-connected-apps-rounded-squares)
=> Apps icon rounded square

source/shared/constants/currencies.js, source/ui/AssetItem/index.jsx
- Removed asset value when token is not cycle or icp based
=> Removed value from assets when not icp or cycle based

source/Pages/Notification/index.jsx
- Replaced onclose with onbeforeunload to make modals throw on close
=> Changed onclose for onbeforeunload

source/ui/NFTDisplayer/index.jsx
- mapping type `image/svg+xml` to `iframe`
The goal is to display animated SVGs correctly within plug. Therefore  the mapping from `image/svg+xml` to `iframe` was provided. **Unfortunately I wasn't able to test this in plug**, as the canister I'm using for test deployment isn't available in DAB and I wasn't able to inject it into plug. As reference I screen captured the above GIF to show that it works in stoic wallet using the following [code](https://github.com/letmejustputthishere/stoic-wallet/blob/807cd055d8d02c1869ad0f0b9f7ac2d1698b075f/src/components/NFTList.js#L391).
If you want to test it on the canister I'm using feel free to leave an address/principal and I'll send a couple of NFTs over. The NFT I'm displaying in the GIF is [this …
=> ✨ display svg's as iframes

source/ui/NFTDisplayer/index.jsx, source/ui/NFTDisplayer/styles.js
- Added spinner for loading NFTs
- [sc-25016](https://app.shortcut.com/terminalsystems/story/25016/fix-add-spinner-to-nfts)
https://user-images.githubusercontent.com/44899916/149842096-f6c171e2-b1b8-4f72-a593-7d293777f74e.mov
- We should probably find a way to cache the media to avoid showing the spinner
=> Added loader for nfts

source/ui/NFTDisplayer/index.jsx
Reverts Psychedelic/plug#343
@letmejustputthishere we need to revert this as it's breaking other svg based collections on firefox browser, causing them to display incorrectly both in the NFT tab and the details page. 
We've tried using `embed` and `object` but seems not to work throwing some CORS errors 🤔
Read in #plug chat that you were able to display it successfully using an `object` tag. Could you elaborate on this a bit more?
=> Revert "✨ display svg's as iframes"

source/Pages/Notification/components/BurnXTC/hooks/useRequests.jsx
- Duplicate burnXTC timeout on rpc endpoint
=> duplicated burn xtc timeout

source/Popup/Views/AddToken/components/CustomToken.jsx
- Fixed bug where we couldn't add custom tokens
https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=5e44fb0e6f864c1c929067486135d86e
We need to do param sanitization in the controller also to use the DAB JS token standards constants. We could do it only on the controller side but I think that would be a bad practice.
=> fix custome token add bug

source/shared/constants/canisters.js
- Added WICP id to the list of protected ids in case DAB fails to fetch tokens.
https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=64d9aaa7cc9c4bee981b6dc3fa96ae2a
=> Fix: Fallback WICP id for canister validation

source/Background/Controller.js, source/Modules/Controller/connection.js, source/Modules/Controller/index.js, source/Modules/index.js, source/Modules/storageManager.js
- Added the `getApp` to the `StorageModule` to avoid using the `getApps` and then extracting a specific app.
- Introduces the `ConnectionModule`, modularizes all the connection related `BackgroundScript` methods (`requestConnect`, `isConnected`, `disconnect`)
- Had to initialize the keyring before exposing the methods to ensure the `keyring` is being passed correctly to the `ConnectionModule`
- Since we are approaching the refactor in steps and don't want to pr the whole refactor I'm going to refactor the `BackgroundScript` itself after modularizing all the methods.
- Ticket 1
- Ticket 2
- Ticket 3
=> ConnectionModule / BackgroundScript refactor

source/Pages/Notification/components/AllowAgent/index.jsx, source/Pages/Notification/components/AppConnection/index.jsx, source/shared/constants/connectionStatus.js, source/ui/ActivityItem/components/items/PlugItem.js, source/ui/ActivityItem/index.jsx
- Added refused to `ConnectionStatus` that way we stop showing `unplugged` when the user rejects the connection to the app.
- Ticket 1
- Ticket 2
- Ticket 3
https://user-images.githubusercontent.com/44899916/165116763-fe17f8f3-33bc-46bf-a178-811e04da76bd.mp4
> On the video we can see how after refusing the connection two times (via cancel button & closing the modal) the activity tab doesn't log anything (as it's supposed to be)
Note that we are storing the refused connection, that way if we want to display it in the future it will work in retroactively . 🚀
=> Refused connection Activity

source/components/Profile/index.jsx, source/components/Profile/styles.js, source/locales/en/translation.json
- Added error message when trying to edit wallet name with name longer than 24 chars
=> Added error message to account creation when name is too long

source/components/ActionDialog/index.jsx, source/components/Apps/index.jsx, source/components/ConnectAccountsModal/components/ConnectAccountItem/index.jsx, source/components/ConnectAccountsModal/index.jsx, source/components/ConnectAccountsModal/layout.jsx, source/components/ContactList/index.jsx, source/components/IDInput/index.jsx, source/components/Profile/index.jsx, source/shared/services/ICNS.js, source/shared/utils/ic/icns/reverse_registrar.did.js
- Added ICNS reverse resolution helper and reverse-resolve names in the modal.
- Changed 'Cancel' to decline
- Execute account switch even if not connecting the new account
- Fixed modal styles
https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=89b0adf157e24dc4b7186dfa2128d489
=> Chore: Account switch improvements

source/components/ConnectAccountsModal/styles.js
- Added max width so ellipsis appears on modal title
- https://www.notion.so/BUG-Fix-connecting-screen-with-long-names-b2e5b32eafa248cc84995e7b08848d42
=> Fix: Switch accounts connect modal title

source/Modules/Controller/transaction.js
- Fixes standard used for requestTransfer transactions to `ROSETTA` (default ICP transactions)
=> Fixed token standard in handleRequestTransfer
