Psychedelic/plug

package.json, yarn.lock
Bump to `plug-controller` v0.0.13 so the double send problem is fixed.
=> Use updated version of plug controller to fix dbl send problem

.storybook/.npmrc
- Adds @Psychedelic scope for Storybook builder
=> fix: 🐛 storybook builder dependency scope

source/Popup/Views/Send/Steps/Step3.jsx, source/Popup/Views/Send/styles.js
- Styling fix on review send
- Ticket 1
- Ticket 2
- Ticket 3
=> Styling fixes on review send

source/components/IDInput/id-input.stories.jsx, source/ui/ActivityItem/SwapIcon/swap-icon.stories.jsx, source/ui/ActivityItem/activity-item.stories.jsx, source/ui/MultiInput/multi-input.stories.jsx
=> fix: 🐛 storybook missing fields

README.md
- Github registry authentication process
=> docs: ✏️ gitHub npm registry access

views/options.html
- Change title Options to Plug (options.html)
- [ch23229](https://app.clubhouse.io/terminalsystems/story/23229/tab-title-is-options)
=> fix: 🐛 change options.html title (Options to Plug)

source/Options/Views/Welcome/styles.js
- Removes unwanted white gap
- [ch23227](https://app.clubhouse.io/terminalsystems/story/23227/create-wallet-complete-screen-on-laptop-sizes-shows-white-under-the-fold)
=> style: 💄 remove unwanted white space bellow gif

source/Popup/Views/Contacts/components/AddContact.jsx, source/Popup/Views/Contacts/hooks/useSteps.jsx, source/Popup/Views/Contacts/styles.js, source/Popup/Views/Send/Steps/Step3.jsx, source/Popup/Views/Send/hooks/utils.js, source/Popup/Views/Send/styles.js, source/hooks/useContacts.jsx, source/locales/en/translation.json
- Contact validation
- fix style
- [CH23207](https://app.clubhouse.io/terminalsystems/story/23207/fix-can-add-same-contact-multiple-times)
- [xas] Chrome
=> Contact validation

source/Background/Keyring.js, source/Popup/Popup.jsx, source/Popup/Views/Contacts/hooks/useSteps.jsx, source/Popup/Views/WalletDetails/index.jsx, source/Popup/Views/WalletDetails/styles.js, source/hooks/useSettingsItems.jsx, source/redux/wallet.js
- Enabled WalletDetails view
- Integrated update principal method
- Ticket 1
- Ticket 2
- Ticket 3
https://user-images.githubusercontent.com/44899916/125534225-a00092e5-a41a-4385-a5b1-a9bd212234db.mov
=> Juan.angarita/ch23066/integrations change wallet name and emoji

source/Popup/Views/Send/Steps/Step1.jsx, source/Popup/Views/Send/hooks/useSteps.jsx, source/Popup/Views/Send/styles.js, source/locales/en/translation.json
- Validate address match current user address
- Add support for Principal ID
- Add support for Address ID
- Related to [ch23136](https://app.clubhouse.io/terminalsystems/story/23136/fix-transactions-to-one-self-are-always-marked-as-received)
=> feat: 🎸 warning on transfer to same address

source/Background/Controller.js
[CH23307](https://app.clubhouse.io/terminalsystems/story/23307/fix-check-for-is-connected-before-logged-in)
=> check for connect before login on balance

package.json, source/Inpage/index.js, yarn.lock
- Update inpage provider version
=> Added new inpage provider version

source/Background/Controller.js, source/Background/utils.js
- Fixed `isConnected` by fixing the state path it was checking
- Added parameter validation to requestTransfer
=> IC Provider API Fixes 1

source/Background/Controller.js, source/Pages/Notification/index.jsx
- [CH23315](https://app.clubhouse.io/terminalsystems/story/23315/fix-close-ic-papi-login-modal-when-redirecting-to-create-import-flow)
=> added is initialized validation

source/Background/Keyring.js, source/Popup/Views/Login/index.jsx, source/Popup/Views/SeedPhrase/Steps/Step2.jsx, source/ui/IncomingAction/index.jsx, source/ui/IncomingAction/styles.js
- fixed horizontal scroll on incoming action
- [CH23331](https://app.clubhouse.io/terminalsystems/story/23331/fix-app-conecction-url-breaks-if-url-too-long)
=> fix horizontal scroll on incoming action

source/Background/Controller.js, source/Popup/Views/Login/styles.js, source/ui/IncomingAction/styles.js
- Fix login height for IC Provider API
=> Made login height 100%

source/locales/en/translation.json, source/ui/ActivityItem/index.jsx, source/ui/ActivityItem/styles.js
- Link to ic.rocks on activity
- Show full account ID / credentials on activity feed
- [CH23258](https://app.clubhouse.io/terminalsystems/story/23258/enhancement-show-full-account-id-credentials-on-activity-feed)
- [CH23258](https://app.clubhouse.io/terminalsystems/story/23258/enhancement-show-full-account-id-credentials-on-activity-feed)
=> copy address and link to ic rocks

source/Options/Views/Welcome/steps/CreatePasswordStep.jsx
- [] Business Logic
- Ticket 1
[CH23262](https://app.clubhouse.io/terminalsystems/story/23262/enhancement-allow-submit-on-enter-on-create-password-step)
=> enter keypress on create password

source/Options/Views/Welcome/steps/CreatePasswordStep.jsx
- [CH23334](https://app.clubhouse.io/terminalsystems/story/23334/fix-previous-contacts-saved-unless-you-remove-extension)
=> clean storage when importing/creating new acc

source/Options/Views/Welcome/steps/CreatePasswordStep.jsx
- Prevented extension storage from being cleared in FF and just clear the contacts
=> Fix contacts clearing

package.json, source/Background/Controller.js, yarn.lock
- Runtime type check for whitelist argument on requestConnect call
- Use plug-inpage-provider, version 1.1.11
- Updated yarn.lock
Pending dependency https://github.com/Psychedelic/plug-inpage-provider/pull/22
=> refactor: 💡 whitelist handling

source/Background/Controller.js
- Added connected validation on sign request
=> Added validation for connection on signing check

source/Background/Controller.js, source/Background/errors.js, source/Pages/Notification/components/AllowAgent/index.jsx, source/Pages/Notification/index.jsx, source/shared/utils/ids.js, source/ui/theme/index.js
- [fix-validate-canister-id-in-papi-connect-modal](https://app.clubhouse.io/terminalsystems/story/23437/fix-validate-canister-id-in-papi-connect-modal)
=> validate canister ids on requests connecte and create agent

source/Popup/Views/Send/Steps/Step3.jsx, source/shared/utils/short-address.js, source/ui/ActivityItem/index.jsx
[enhance-show-longer-addresses](https://app.clubhouse.io/terminalsystems/story/23332/enhance-show-longer-addresses)
=> show longer address everywhere

source/Popup/Views/AddToken/components/CustomToken.jsx, source/Popup/Views/Contacts/components/AddContact.jsx, source/components/IDInput/index.jsx, source/ui/ActivityItem/styles.js
- added trim to some inputs
- fix activity style
- [enhancement-add-trim-to-textboxes](https://app.clubhouse.io/terminalsystems/story/23261/enhancement-add-trim-to-textboxes)
=> added trim to inputs

source/Background/Keyring.js, source/shared/utils/short-address.js, source/ui/ActivityItem/index.jsx
- [CH23523](https://app.clubhouse.io/terminalsystems/story/23523/fix-change-principal-id-format)
=> Display shorter address like before

package.json, source/Background/Keyring.js, source/components/ConnectionStatus/index.jsx, source/components/Layout/index.jsx, source/manifest.json, source/shared/constants/connectionStatus.js
- [CH23524](https://app.clubhouse.io/terminalsystems/story/23524/feature-display-app-conection-in-header)
=> Display connection status

README.md
- Add details on how to install from browser extension stores
- None
=> Readme update - New download links

source/Popup/Views/Send/Steps/Step3/index.jsx
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> Fixed price on step3

package.json, source/Background/Keyring.js, source/locales/en/translation.json, source/redux/wallet.js, source/shared/constants/activity.js, source/shared/constants/currencies.js, source/ui/ActivityItem/index.jsx, yarn.lock
- Added XTC transaction history
- Added Mint and Burn cases to activity items
- Fixed date and asset formatting in wallet reducer
https://app.clubhouse.io/terminalsystems/story/23453/feature-v3-refactor-gettransactions-to-work-with-xtc
- Missing Mint and Burn symbols
=> XTC History

package.json, source/assets/icons/burn-activity.svg, source/ui/ActivityItem/index.jsx, source/ui/GenericIcon/index.jsx, yarn.lock
- Add burn icon
- Rename mint to receive
- Updated wallet
=> Added Burn icon, renamed mint to receive, update controller version

package.json, yarn.lock
=> Updated package to fix xtc burn

source/Background/Controller.js, source/Background/Keyring.js, source/Pages/Notification/components/Transfer/hooks/useRequests.jsx, source/Pages/Notification/components/Transfer/index.jsx
=> Added loading and prevent modal close on error

package.json, source/Background/Keyring.js, source/Pages/Notification/components/Transfer/index.jsx, yarn.lock
=> 0.3.0 fixes

source/Popup/Views/Home/index.jsx, source/components/Router/Router.js
Fixed when changing subaccounts it didnt redirect to tokens
[CH23795](https://app.clubhouse.io/terminalsystems/story/23795/fix-redirect-when-changing-subaccounts)
=> [CH23795] Fixed navigator issue

package.json, source/Background/Keyring.js, source/Popup/Views/Login/index.jsx, source/Popup/Views/NFTDetails/index.jsx, source/components/Tokens/index.jsx, source/manifest.json, source/redux/wallet.js, source/shared/constants/currencies.js, source/ui/AssetItem/index.jsx, source/ui/AssetItem/styles.js, yarn.lock
- Added assets cache and refresh logic
- Removed spinning loader and added pulsing texts instead
https://app.clubhouse.io/terminalsystems/story/23263/enhancement-cache-assets-in-storage
- WIP - need to deploy controller
=> Added assets caching and enable kyashu cors for firefox

source/Popup/Views/NFTDetails/index.jsx, source/shared/constants/urls.js
- Enable button with link to icpunk mkplace
https://app.clubhouse.io/terminalsystems/story/23824/fix-enable-ic-punks-marketplace-button
=> Added redirect to icpunks marketplace

source/Pages/Notification/components/AllowAgent/index.jsx, source/Pages/Notification/components/AppConnection/index.jsx, source/Pages/Notification/components/Transfer/index.jsx, source/components/Layout/index.jsx, yarn.lock
It wasnt showing pid and wallet name
[CH23794](https://app.clubhouse.io/terminalsystems/story/23794/fix-ic-papi-connect-header)
=> [FIX] IC PAPI - Connect header

source/Popup/Views/AddToken/Steps/Step2.jsx
- Remove 0 when no price available
Before: 
After
=> Fix Add custom token 

source/Popup/Views/Send/Steps/Step1.jsx
=> [FIX] fixed amount inconsistency when using max button

package.json, source/manifest.json
=> Updated version to 0.3.2

source/hooks/useApps.jsx
Subaccounts were sharing connected apps
=> [Fix] Connected Apps

source/Popup/Views/AddToken/Steps/Step2.jsx, source/hooks/useApps.jsx
[CH23871](https://app.clubhouse.io/terminalsystems/story/23871/fix-show-custom-token-instantly-after-adding-it)
=> [FIX] show custom token instantly after adding it

source/Background/Keyring.js, source/Popup/Views/Send/Steps/Step3/index.jsx, source/Popup/Views/Send/hooks/useSteps.jsx, source/components/Profile/index.jsx, source/components/Tokens/index.jsx, source/shared/constants/addresses.js
- Added assets refresh on send
=> Added assets refresh on send

source/Pages/Notification/components/BurnXTC/index.jsx, yarn.lock
- Adds current account to header
- Ticket 1
- Ticket 2
- Ticket 3
=> [FIX] Added current account to header

source/components/NFTs/index.jsx, source/redux/wallet.js
-  Fixed redux update after send NFT
- Added sync update to nfts screen
https://app.shortcut.com/terminalsystems/story/23949/fix-nfts-refresh-after-update
=> Fixed redux update and added sync update to screen

package.json, source/Options/Views/Welcome/steps/CreatePasswordStep.jsx, source/Popup/Views/ExportIdentity/steps/Step2.jsx, source/components/Profile/index.jsx, source/components/UserIcon/index.jsx, source/components/UserIcon/styles.js, source/shared/constants/emojis.js, yarn.lock
- Bumped `@psychedelic/plug-controller` to `0.5.2`
- Default emoji adding into PlugWallet on first time account creation
- Chrome sidebar emoji centered
- https://app.shortcut.com/terminalsystems/story/23851/fix-default-account-emoji
https://user-images.githubusercontent.com/32408893/133897412-ac0aa129-bc16-4e9a-b8a8-6aa69b80f234.mov
=> Default account emoji on creation

package.json, source/Background/Keyring.js, source/Popup/Views/Home/index.jsx, source/components/NFTs/index.jsx, source/redux/wallet.js, yarn.lock
- Added new controller version with NFT Lock
- Fixed collections loading to work with new fix
https://app.shortcut.com/terminalsystems/story/23975/fix-0-3-3-firefox-latency-bugged-ui
Improvement rather than fix, but it works much better.
=> Updated controller version, fixed collections loading

package.json, source/Popup/Views/AddToken/components/CustomToken.jsx, source/Popup/Views/AddToken/components/DabComingSoon.jsx, source/Popup/Views/Deposit/Steps/Step2.jsx, source/Popup/Views/Login/index.jsx, source/Popup/Views/NFTDetails/index.jsx, source/Popup/Views/Send/Steps/Step3/index.jsx, source/Popup/Views/WalletDetails/index.jsx, source/Popup/index.jsx, source/ui/ActivityItem/index.jsx, source/ui/WhitelistItem/index.jsx, webpack.config.js, webpack.inpage.js, yarn.lock
- Removed `webextension-polyfill`
- Replaced `webextension-polyfill` usage by `extensionizer`
=> Webextension polyfill replaced by extensionizer

.vscode/settings.json, jsconfig.json, source/Inpage/index.js, source/components/ConnectionStatus/index.jsx, source/locales/en/translation.json
- Grabbed extensions version from manifest
- Displayed version on the popup
- https://app.shortcut.com/terminalsystems/story/23737/papi-provide-a-way-of-reading-the-version-number
=> Plug extension version added

source/Popup/Views/NFTDetails/index.jsx, source/Popup/Views/SendNFT/index.jsx, source/components/NFTs/components/NFTCollection/index.jsx, source/components/TokenIcon/index.js, source/ui/NFTDisplayer/index.jsx, source/ui/Select/index.jsx, source/ui/index.js
- Adds support for video NFTS
- Checks the `Content-Type` of the `nft` allowing for types different than video or images
- Ticket 1
- Ticket 2
- Ticket 3
https://user-images.githubusercontent.com/44899916/135177425-919ca5bb-457b-42a5-900d-c713afcefb32.mov
=> Support for video NFTS

source/Background/Controller.js
- Canister info fallback
- https://app.shortcut.com/terminalsystems/story/24040/v4-get-canister-names-on-connect-modal
- https://app.shortcut.com/terminalsystems/story/24041/v4-get-canister-names-on-apps-tab
=> Canister info fallback

source/Pages/Notification/components/AllowAgent/index.jsx, source/Pages/Notification/components/AllowAgent/styles.js, source/locales/en/translation.json, source/ui/CanisterInfo/components/Container/styles.js, source/ui/CanisterInfo/components/Item/index.jsx, source/ui/CanisterInfo/components/Item/styles.js, source/ui/IncomingAction/styles.js, views/notification.html
[SC24121](https://app.shortcut.com/terminalsystems/story/24121/new-request-connect-styles)
=> [SC24121] new request connect whitelist styles

source/Background/Controller.js, source/Background/Keyring.js, source/Popup/app.jsx
- Fixed keyring problem when enabling/disabling extension
=> Fixed keyring problem when disable/enable extension

yarn.lock
=> Yarn lock re-generation

package.json, source/Background/Controller.js, source/hooks/useApps.jsx, source/shared/utils/apps.js, yarn.lock
- Exposed disconnect controller
- Added `removeAppsByURL` utility function to `utils`
- https://app.shortcut.com/terminalsystems/story/24130/v4-ic-papi-disconnect
**Please do not merge before releasing the `plug-inpage-provider`'s** https://github.com/Psychedelic/plug-inpage-provider/pull/44
=> Exposed disconnect controller, apps utils

source/Options/Views/Welcome/steps/CreatePasswordStep.jsx
- Clears the storage on create account
- Ticket 1
- Ticket 2
- Ticket 3
=> Clears storage on create account

package.json, source/Background/Controller.js, source/components/NavBar/index.jsx, source/redux/icp.js, yarn.lock
- Audit fixes
- [24215](https://app.shortcut.com/terminalsystems/story/24215/v4-1-audit-fixes)
=> v4 1 Audit fixes [sc-24215]

package.json, source/manifest.json
=> Bump versions

package.json, source/Background/Keyring.js, source/redux/wallet.js, source/shared/utils/ids.js, source/ui/ActivityItem/index.jsx, source/ui/GenericIcon/index.jsx, yarn.lock
=> Fix transaction history integration

source/manifest.json
Updated url to make firefox cors work
=> Updated kyasshu url

package.json, yarn.lock
- Add new controller version with storage fix to prevent the `StandardNotImplemented` method.
=> Install package. Update version

package.json, source/Background/Controller.js, source/hooks/useActivity.jsx, source/hooks/useApps.jsx, source/locales/en/translation.json, source/shared/constants/connectionStatus.js, source/shared/constants/currencies.js, source/shared/utils/apps.js, source/ui/ActivityItem/index.jsx, source/ui/AppItem/index.jsx, source/ui/GenericIcon/index.jsx, yarn.lock
- App history doesnt delete when disconnecting from app
- Now shows Unplugged from when disconnecting 
- [improvement-suggestion-activity-tab](https://app.shortcut.com/terminalsystems/story/24510/improvement-suggestion-activity-tab)
=> historic app activity and apps separated

source/Background/Keyring.js, source/components/Profile/index.jsx, source/components/Tokens/index.jsx, source/redux/wallet.js, source/ui/AssetItem/index.jsx, yarn.lock
- Parse asset amount to number to fix issue where no loading was shown and assets were never refreshed.
- Fetch assets automatically every 15 seconds
-
https://app.shortcut.com/terminalsystems/story/24576/add-loading-message-icon-when-icp-is-received
=> Asset refresh fix

source/Popup/Views/AddToken/Steps/Step2.jsx, source/Popup/Views/SendNFT/index.jsx
- fix send nft throwing error everytime
- fix amount value displayed on add custom token
[24669](https://app.shortcut.com/terminalsystems/story/24669/fix-send-nft-always-shows-an-error)
[24668](https://app.shortcut.com/terminalsystems/story/24668/fix-search-token-decimal-parsing)
=> Fix send nft + fix add custom token amount

source/Pages/Notification/components/Sign/components/Details/utils.js
- Fix decimals parsing in sign and batch transactions modal.
=> Added decimal parsing to sign modals

package.json, source/redux/wallet.js
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> fix: use new plug controller and get symbol

yarn.lock
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> fix: add plug-controller new package

source/Background/Controller.js, source/redux/profile.js
- Divide amount by E8S_PER_ICP
- Parse amount as string
=> Fixed request transfer issue with amount parsing

source/ui/ActivityItem/SwapIcon/index.jsx, source/ui/ActivityItem/index.jsx
- Activity crash fix
- Ticket 1
- Ticket 2
- Ticket 3
=> Fixed activity crash on unknown info on currency

source/Background/Keyring.js
- Fixed unexpected error when trying to get assets
- Ticket 1
- Ticket 2
- Ticket 3
=> Checked if keyring is unlocked before trying to get assets

source/components/Tokens/index.jsx, source/components/Tokens/styles.js, source/ui/Dialog/index.jsx, source/ui/Dialog/styles.js
- Add custom token button always showed at the bottom
- Fix overflow on all dialogs
=> fix: button and overflow fixes

package.json, yarn.lock
Added new inpage version with chain transactions by @maksym-boytsov
=> Added new inpage version

package.json, yarn.lock
- Prevents app from crashing on failed balance call
- Fixes typing issue on storage load and save
=> Fix custom token storage issues [Update Controller to 0.13.2]

source/Popup/Views/Home/index.jsx, source/Popup/Views/SendNFT/index.jsx
- Fixes NFT optimistic rendering
- Removed NFT fetching from `home`
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
https://user-images.githubusercontent.com/44899916/147982925-dedf1581-7b39-4c9a-ad1b-a7dcf5733d16.mov
=> NFT optimistic rendering

source/Pages/Notification/components/BurnXTC/index.jsx, source/Pages/Notification/components/Sign/components/BatchTransactions/index.jsx, source/Pages/Notification/components/Sign/index.jsx, source/Pages/Notification/components/Transfer/index.jsx, source/Popup/Views/AddToken/components/CustomToken.jsx, source/locales/en/translation.json
- Removed decline callbacks as they are being handled by the onbeforeunload
=> Removed onDecline callbacks 

package.json, source/Popup/Views/Home/index.jsx, source/Popup/Views/SendNFT/index.jsx, source/components/Tokens/styles.js, yarn.lock
Update controller to fix XTC history issues and EXT NFT failed transfers
=> Installed controller 0.13.3

source/components/Tokens/index.jsx, source/components/Tokens/styles.js
- [Ticket 1](https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=ddf5a72b23d94732b49adc62c7d6477f)
=> feature: new add custom token button

source/Pages/Notification/components/Sign/components/Details/utils.js
=> Rename "SwapExactTokenForTokens" to "Swap Tokens”

source/shared/constants/currencies.js
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> Fixed on empty fail

package.json, source/Pages/Notification/components/BurnXTC/styles.js, source/Pages/Notification/components/Sign/components/BatchTransactions/styles.js, source/Pages/Notification/components/Sign/styles.js, source/Pages/Notification/components/Transfer/styles.js, views/notification.html
- pump version to 0.4.6
- fix overflow on notification window
[- Ticket 1](https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=1db4d15e55ee4ed1a5fa105e7531e219)
=> Notification window overflow fix

package.json, yarn.lock
Update controller version to 0.14.2
=> Installed controller 0.14.2

source/Popup/Views/SendNFT/index.jsx
- Fixed issue where the whole nft collection was being filtered after an nft was sent.
- [notion-ticket](https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=c56d714ca60f45f5b47bced64c7a5edd)
https://user-images.githubusercontent.com/44899916/151248476-01f4a9a0-4fd7-49f4-9b38-8c71aef48e7c.mov
=> Fixed wrong filter

yarn.lock
Updated lcokfile for inpage 0.16,3
=> Updated lockfile

package.json, yarn.lock
=> Installed provider 1.6.2

source/hooks/useApps.jsx
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> fix: url typo in to disconnect

package.json
=> Revert "Added resolutions to pass audit"

source/components/Tokens/styles.js, yarn.lock
- Centered add token button 🙃
- Ticket 1
- Ticket 2
- Ticket 3
=> Centered button

source/ui/NFTDisplayer/index.jsx
- Made spinner responsive.
- Ticket 1
- Ticket 2
- Ticket 3
=> Made spinner responsive

source/Popup/Views/AddToken/components/CustomToken.jsx, yarn.lock
Fix issue where continue button would disable if incorrect token interface is found
- Enable button even if `tokenError` is true.
- Remove token error if input or select changes.
https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=f3e709c46e80478da807c4d75238e774
=> Fix: Custom Token add screen lock

source/Popup/Views/Send/Steps/Step3.jsx, source/Popup/Views/Send/hooks/useSteps.jsx, source/Popup/Views/Send/styles.js, source/ui/MultiInput/index.jsx
- Removed total values when the token price is unknown in send flow confirmation.
- Disabled currency swapping on send flow for tokens without a known price
https://user-images.githubusercontent.com/12738697/154106760-73807680-5628-4a53-819e-74e3163f62ac.mov
=> Fix: Token values on send flow for unknown price

package.json, yarn.lock
Updated provider to v1.7.0 including principal, accountid and agent auto refresh
=> Update provider to 1.7.0

source/Background/Keyring.js, yarn.lock
- Fixes bug I introduced myself 👍 
- Ticket 1
- Ticket 2
- Ticket 3
=> Fix wrong token send

source/ui/NFTDisplayer/index.jsx
- Added specific SVG support so BTC flowers that are the most expensive NFT in entrepot appears in plug and it is compatible with other nfts
=> added svg support

README.md
-changed the documentation of the npm registry following a correction
=> updated NPM registry in readme

source/shared/constants/urls.js, source/ui/ActivityItem/index.jsx
- Change TX link from ic rocks to https://dashboard.internetcomputer.org/
[- Ticket 1](https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=9fda8c61796241ccbdcb916a1a667fc7)
=> updated ICRocks TX link to ic.org dashboard

package.json, yarn.lock
#chore: bump controller version
=> chore: bump controller version

source/Popup/Views/Home/index.jsx, source/Popup/Views/Login/index.jsx, source/Popup/Views/SendNFT/components/NFTDisplay/index.jsx, source/shared/utils/time.js
Removed clock check i home screen. Fixed nft display on rwview send nft screen
=> Fix: 0.5 fixes

package.json, yarn.lock
=> Update controller with sonic info serialization fix

source/manifest.json, source/shared/utils/time.js
- Fixed manifest for CORS errors. 
- Added cache flush to time request to prevent cached responses causing issues.
-  Reduced diff to 2minutes
=> Fix: Clock reset issue

source/Popup/Views/Home/index.jsx
- Added missing else causing clock validation to fire even if not logged in
=> Fix: Clock error login

source/components/NFTs/components/NFTCollection/index.jsx, source/components/NFTs/components/NFTCollection/styles.js, source/components/NFTs/styles.js
- Refactored NFT Tab view.
- https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=d46ce004bd144ea38efe9544ee289812
https://user-images.githubusercontent.com/84542297/160625601-3ec199cc-f889-4d9e-bd13-ca652462542a.mov
=> Refactored nft screen styles

package.json, yarn.lock
- Updated controller and dab-js to use latest version including dip721v2 update.
https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=be937c871d32475e835321dbd488890c
=> Fix: DIP721v2 

package.json, source/Background/Controller.js, source/Inpage/index.js, source/Pages/Notification/components/LoginProxy/index.jsx, source/Pages/Notification/index.jsx, yarn.lock
- Updated provider connection flow to store and retrieve whitelist host and timeout from storage. 
- Added public key serialization to connection flow
- Refactored balance provider modal into a generic login proxy modal which proxies calls back to the extension on login.
- https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=97d39b40d8fc49ba9c81e7c7f51e6ae9
=> [WIP] Improvement: Provider connection flow

.eslintrc.js, package.json, source/Background/Controller.js, source/Background/utils.js, source/Modules/Controller/connection.js, source/Modules/index.js, source/Modules/storageManager.js, yarn.lock
- Remove calls to DAB in signature requests, causing performance downgrades.
- Add protected id request on initialization and connection.
- Add protected ids storage handlers.
- Refactored request sign to improve storage fetch and improve performance.
https://www.notion.so/Plug-Extension-631a299f3ec14b9c9522e29a9800e923?p=94c8040ad71c416d844c1549647c0719
- Average performance diff:
=> Chore: enhance provider performance

source/Background/Controller.js
Implement function to displayPopUps
=> refactor: add function to display popUp

package.json, source/Modules/Controller/connection.js, yarn.lock
- Added new inpage provider with host fixes
- Added host as a parameter in requestConnect and serialize it in storage
=> Fix: Serialize host in provider connection

package.json, source/Background/utils.js, source/Modules/Controller/transaction.js, source/Pages/Notification/components/Transfer/components/Details.jsx, source/Pages/Notification/components/Transfer/hooks/useRequests.jsx, source/Pages/Notification/components/Transfer/index.jsx, yarn.lock
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> feat: implement requestTransferToken handler

source/Popup/Views/Home/index.jsx, source/Popup/Views/WalletDetails/components/ICNSSelector/index.jsx, source/components/Profile/index.jsx, source/redux/icns.js
- Fixes issue where ICNS info would not be properly updated when changing subaccounts
=> Fixed lag on icns info when switching subaccounts

source/Modules/Controller/connection.js, source/Modules/Controller/controllerBase.js, source/Pages/Notification/index.jsx
- Fixed notification popup rendering issue
=> Removed url parameter causing it to fail to render notification oppup

source/components/Profile/index.jsx, source/ui/HoverAnimation/index.jsx, source/ui/HoverAnimation/styles.js
read commit messages
too hard to screencapture, need to try it out yourself
feels better hovering, no more jank on the edge
=> [bug] Fix profile icon hover animation stutter.

source/components/NavBar/index.jsx, source/components/TokenIcon/index.js, source/ui/MenuItem/index.jsx
read the commit messages
Just booted up project on localhost and found some errors in logs. Cleaned them up.
=> [bug] Fix PropType errors.

source/components/IDInput/index.jsx
- Handles error where you could add as a contact an invalid icns name
- Ticket 1
- Ticket 2
- Ticket 3
=> Can't add to contact if loading icns

source/Modules/Controller/transaction.js
- Fixed batchTransactions reject
- Ticket 1
- Ticket 2
- Ticket 3
=> Only close modal on accepted connection

source/Modules/Controller/transaction.js
- Fixes requestTransfer timeout
- Ticket 1
- Ticket 2
- Ticket 3
=> Added missing currency map

source/Modules/Controller/transaction.js
- Throw on reject/cancel for `requestBurnXTC` & `requestTransfer`
- Ticket 1
- Ticket 2
- Ticket 3
=> Throw on reject when requestTransfer/burn

source/Background/Keyring.js, source/Background/script.js
Removed wwallet serialization from create response as it was somehow causing it to crash FF
=> Fix: Create Account [FF]

source/Background/Keyring.js, source/Background/script.js
Added recursive parse bigint to keyring response handler
=> Fix: FF Bigint parsing in keyring handler

source/shared/services/ICNS.js
- Fixed issue where setting and removing a resolution for a principal would crash icns integration
=> Fix: ICNS set-remove issue

package.json, yarn.lock
- Fix canister id is invalid issue
=> Installed new controller with storage update

source/Popup/Views/WalletDetails/index.jsx
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> Remove reverse resolve name when toggling off.

source/Popup/Views/SendNFT/components/InputStep/index.jsx, source/Popup/Views/SendNFT/components/InputStep/styles.js
- Don't allow send nft to same address, including icns name.
- Ticket 1
- Ticket 2
- Ticket 3
=> Added validation on send nft input

package.json, tests/setup/jestSetup.js, yarn.lock
- Added read from `.env` secrets
Secrets can now be setup using a `.env` file in the root folder
```.env
// .env
SEEDPHRASE=""
SUB_ACCOUNT_ID=""
PASSWORD=""
```
- Ticket 1
- Ticket 2
- Ticket 3
=> Added secrets to .env file

source/Popup/Views/NFTDetails/index.jsx, source/Popup/Views/SendNFT/components/InputStep/index.jsx, source/Popup/Views/SendNFT/components/NFTDisplay/index.jsx, source/components/NFTs/components/NFTCollection/index.jsx, source/components/TokenIcon/index.js, source/shared/constants/nft.js, source/ui/NFTDisplayer/index.jsx, source/ui/Select/index.jsx, yarn.lock
- Added fix for btc flower display
- Ticket 1
- Ticket 2
- Ticket 3
=> Added defaultNftTag for svg display fix

source/Popup/Views/Home/index.jsx, source/components/Profile/index.jsx
- Added lastFocusedTab param to query on chrome tabs
=> Fix: Multiple window connection issues

source/Popup/Views/Contacts/index.jsx
- Fixes contacts for good
- Ticket 1
- Ticket 2
- Ticket 3
=> Added getContacts on contact screen

package.json, yarn.lock
- Uses `plug-controller` v0.17.0 including fetch fallback fixes
=> Updated controller to 0.17 including fallback fix

package.json, source/Background/Keyring.js, source/Popup/Views/SeedPhrase/Steps/Step1.jsx, source/Popup/Views/SeedPhrase/Steps/Step2.jsx, source/Popup/Views/SeedPhrase/hooks/useSteps.jsx, source/components/Tokens/index.jsx, source/manifest.json, yarn.lock
- Removes the need for ICP Price in order to show token balances
=> Removed icpPrice dependency on tokens screen

.eslintrc.js, source/Popup/Views/AddToken/Steps/Step1.jsx, source/Popup/Views/AddToken/Steps/Step2.jsx, source/Popup/Views/AddToken/components/CustomToken.jsx, source/components/Tokens/index.jsx, source/ui/AssetItem/index.jsx, source/ui/Select/index.jsx, source/ui/Tabs/index.jsx, tests/e2e/send-custom-tokens.test.js, tests/e2e/send.test.js, tests/setup/jestSetup.js
- Adding a custom token
- Send custom token
Tests running video:
https://user-images.githubusercontent.com/33018206/176251713-16b18159-6ee4-4f25-a776-5a8c7d4808b5.mov
=> Custom Token Send Flow

source/components/NFTs/components/NFTCollection/index.jsx, source/components/NFTs/components/NFTCollection/styles.js
- [Bug] Add number of NFTs in list
=> Added number of NFT qty collection

source/Popup/Views/Send/Steps/Step1.jsx, source/Popup/Views/Send/hooks/useSteps.jsx
- https://www.notion.so/BUG-Check-icns-name-before-send-f5aaba487b984782a847b7616b345229
=> Checks if the icns is the same as your account when send

source/Options/Views/Welcome/steps/CreatePasswordStep.jsx
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> removed 12 to 8

source/locales/en/translation.json
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> changed 12characters to 8 in descs

source/Popup/Views/Help/index.jsx, source/components/Profile/index.jsx, source/ui/MenuItem/index.jsx, tests/e2e/help.test.js, tests/e2e/send-nft.test.js, tests/setup/jestSetup.js
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
https://user-images.githubusercontent.com/33018206/182913032-41d2f3d5-22c1-4307-93b4-ba1a9e49b809.mov
=> Test/ Settings: Help

source/Popup/Views/ExportIdentity/hooks/useSteps.jsx, source/Popup/Views/ExportIdentity/steps/Step1.jsx, source/Popup/Views/ExportIdentity/steps/Step2.jsx, source/Popup/Views/Settings/index.jsx, source/ui/CodeBox/index.jsx, source/ui/Header/index.jsx, source/ui/Select/index.jsx, tests/e2e/export-dfx-identity.test.js, tests/setup/jestSetup.js
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
https://user-images.githubusercontent.com/33018206/182858300-2bda70f4-603d-45b1-9476-6ac28d4126f9.mov
https://user-images.githubusercontent.com/33018206/182858394-4d42aadc-aca0-4b42-8670-165c1977a465.mov
In the full tests running, the last test case still failed due to a bug with the random wallet locking. Made a video where each case was run separately to ensure they passed testing. 
=> Test/Settings: Export DFX Identity 

tests/e2e/edit-account.test.js, tests/e2e/export-dfx-identity.test.js, tests/e2e/import-create-account.test.js, tests/e2e/secret-recovery-phrase.test.js, tests/e2e/send-nft.test.js
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> fix: fixes for made tests passed

package.json, source/Background/utils.js, source/Modules/Controller/transaction.js, source/components/NFTs/components/NFTCollection/index.jsx, source/components/NFTs/components/NFTCollection/styles.js, yarn.lock
- Installed controller with agent host fix. 
- Await agent calls on provider handlers.
- Removed extra margin from nft collections
=> Fix: Provider agent transactions

source/redux/wallet.js, source/ui/ActivityItem/components/items/NFTItem.js
- Fixed activity icons
- Ticket 1
- Ticket 2
- Ticket 3
=> Fixed deposit & NFT icons in activity

source/Background/Keyring/index.js, source/Pages/Notification/components/Sign/index.jsx, source/Popup/Views/WalletDetails/index.jsx, source/Popup/Views/WalletDetails/styles.js
- Fixed ICNS reverse resolution update by fixing name and params format.
- Fixed ICNS toggle styles for when user has an actively resolved name.
- Fixed contacts integration params formatting
https://user-images.githubusercontent.com/12738697/183892345-71e8cbf3-df40-4253-837a-22f93c7892b1.mov
=> Fixed ICNS reverse resolution updating and styles

source/shared/utils/contacts.js
- Fixes Principal id parsing from contacts
- Ticket 1
- Ticket 2
- Ticket 3
=> Parsed principal id from contacts

source/Modules/Controller/connection.js
- Change 1
- Change 2
- Change 3
- Ticket 1
- Ticket 2
- Ticket 3
=> fix: dont ovewritte whitelist in case is another one present

source/Background/Keyring/index.js, source/shared/constants/currencies.js, source/views/Popup/components/Sign/components/Details/components/AssetDisplay.jsx, source/views/Popup/components/Sign/components/Details/utils.js
- Refactor flow to use standard-based parsing.
- Adds support for new icp ledger interface
- https://github.com/Psychedelic/plug/issues/544
=> Fix: Generic ICP transaction modal parsing

source/components/ConnectionStatus/components/ConnectionControls/index.jsx, source/redux/icp.js, source/views/Extension/Views/SendFlow/hooks/useSteps.jsx, source/views/Extension/Views/SendFlow/steps/selectAsset/index.jsx, tests/e2e/edit-account.test.js, tests/e2e/help.test.js, tests/e2e/send-tokens.test.js
- The token selection logic changed @maksym-boytsov 
- Skeleton added for selected token amount
- Tests fixed
=> Token selection logic / Tests fixes
